### ISSUE TITLE
Clicking on blog menu header results in download of file

### ISSUE THREAD

**Issue by justinjbird** [dataplat/DataSaturdays#434]
Weird issue...accessing https://blog.datasaturdays.com/ either directly or from menu item on https://datasaturdays.com auto-downloads livedevelop.mp4. Brave, Edge, Chrome all exhibit this behaviour but Safari does not #weird browsers are on MacOS on an M2 Mac, everything up to date etc.

![CleanShot-20230413-210417](https://user-images.githubusercontent.com/42351666/231871674-c0184dfb-a05b-4c9d-b389-549ad92fd2be.gif)

**Comment by spaghettidba** [comment]
The file comes from https://blog.robsewell.com/assets/uploads/2021/livedevelop.mp4
It's weird. I couldn't find that file referenced anywhere in the datasaturdays repository, so it must be coming from the jekyll files.
@SQLDBAWithABeard any ideas?

**Comment by SQLDBAWithABeard** [comment]
Well that is very weird. The blog is hosted in a different repo - let me check what is going on

**Comment by SQLDBAWithABeard** [comment]
very strange. The blog is in the repo here https://github.com/dataplat/datasaturdays-blog 

The mp4 is on this page and loaded vvia an iframe

https://github.com/dataplat/datasaturdays-blog/blob/d634e712628efc7c4c951208a9d967042ce1f440/_posts/2021-04-15-locally-viewing-github-pages-new-data-saturdays.md?plain=1#L71

So have changed that

**Comment by spaghettidba** [comment]
Thank you Rob!

**Comment by SQLDBAWithABeard** [comment]
Appears to be fixed now with [92b64a2080cfaf34f8fde8c9f751fb8201cc958a](https://github.com/dataplat/datasaturdays-blog/commit/92b64a2080cfaf34f8fde8c9f751fb8201cc958a)
