### ISSUE TITLE
Vulnerabilities and temp files

### ISSUE THREAD

**Issue by spaghettidba** [dataplat/DataSaturdays#439]
See https://github.com/dataplat/DataSaturdays/security/secret-scanning/1
Some files are in /temp and they should probably not be there? 
@SQLDBAWithABeard what do you think?

**Comment by SQLDBAWithABeard** [comment]
Thats the API key for Parma to show the map. The temp file is created for each run just in case something screwy happens. I'm not so worried about the temp files but maybe we need to ping @solid-bases to check the google maps API key ??

**Comment by SQLDBAWithABeard** [comment]
I turned on secret scanning for the repos that I maintain, just to be safe and this has come up in the first scan. It does come from the first Parma event also.

Let me know what you wish. I can make it disappear from here and from the history if you like or it can be left. It is up to you (Well, Alessandro I guess!)

**Comment by solid-bases** [comment]
I confirm, Alessandro is aware and accepts the risks, you can leave it there 😄

**Comment by SQLDBAWithABeard** [comment]
Awesome,  thank you for checking.
