### ISSUE TITLE
Data Saturday Cape Town

### ISSUE THREAD

**Issue by jody1979** [dataplat/DataSaturdays#477]
### eventname

Data Saturday Cape Town

### date

2023-08-12 08:00:00 -16:00

### description

Data Saturday is a free community‐focused event dedicated to educating and engaging members of the local technical and business community. Data Saturday draws upon the expertise of local and international data professionals, developers and solutions architects and business users who come together to share their real-world experiences, lessons learned, best practices, and general knowledge with other like‐minded individuals.

### registrationurl

https://www.eventbrite.com/e/data-saturday-cape-town-tickets-657452266427

### rooms

roomname1;roomurl1,roomname2;roomurl2,roomname3;roomurl3

### sponsors

sponsor1link;sponsor1image;sponsor1height,sponsor2link;sponsor2image;sponsor2height,sponsor3link;sponsor3image;sponsor3height

### speakerlisturl

https://sessionize.com/data-saturday-cape-town-2023

### organizers

organizer1name;organizer1twitter;organizer1email,organizer2name;organizer2twitter;organizer2email,organizer3name;organizer3twitter;organizer3email

**Comment by SQLDBAWithABeard** [comment]
cos we had an open PR, I need to close this and redo with #479  @jody1979
